# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tcGcaJz79x0PaUeaSUOYpduTv3fWQcFb
"""

#Ejercicio 1

conjuntoA = {1, 2, 3, 4}
conjuntoB = {3, 4, 5, 6}

print(conjuntoA | conjuntoB)

#Ejercicio 2

conjuntoA = {4, 2, 7, 8}
conjuntoB = {8, 6, 5, 2}

print(conjuntoA & conjuntoB)

#Ejercicio 3

conjuntoA = {9, 10, 11, 12}
conjuntoB = {11, 12, 13, 14}

print(conjuntoA.symmetric_difference(conjuntoB))

#Ejercicio 4

conjuntoA = {21, 24}
conjuntoB = {21, 22, 23, 24}

print(conjuntoA.issubset(conjuntoB))

#Ejercicio 5

conjuntoA = {11, 55, 33, 44, 22}

print(len(conjuntoA))